=== mxu/ConditionEditor/app/data/condition.dtd
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Tony Hardee (Perot Systems) -->
<!ENTITY % response "(free_form_response|item_response|table_response)?">
<!ENTITY % restriced_service "(restricted_state|restricted_country)">
<!ENTITY % physician_ref "(physician_id|physician)">
<!ELEMENT divisions (division+)>
<!ELEMENT division (department+)>
<!ATTLIST division
	name CDATA #REQUIRED
	description CDATA #REQUIRED
>
<!ELEMENT department (section+)>
<!ATTLIST department
	name CDATA #REQUIRED
	description CDATA #REQUIRED
>
<!ELEMENT section (condition+)>
<!ATTLIST section
	name CDATA #REQUIRED
	description CDATA #REQUIRED
>
<!ELEMENT condition (keyword*, questionnaire, material_list)>
<!ATTLIST condition
	id CDATA #REQUIRED
	active (true | false) "true"
	cost CDATA #REQUIRED
	description CDATA #REQUIRED
	product_id CDATA #IMPLIED
>
<!ELEMENT keyword EMPTY>
<!ATTLIST keyword
	text CDATA #REQUIRED
>
<!ELEMENT questionnaire (question_group+)>
<!ELEMENT question_group (question+)>
<!ATTLIST question_group
	name CDATA #REQUIRED
>
<!ELEMENT question (%response;)>
<!ATTLIST question
	prompt CDATA #REQUIRED
	id CDATA #IMPLIED
	callout CDATA #IMPLIED
	mandatory (true | false) "true"
>
<!ELEMENT free_form_response EMPTY>
<!ATTLIST free_form_response
	response CDATA #IMPLIED
	height CDATA "1"
	width CDATA "80"
>

<!ELEMENT item_response (selection*)>
<!ATTLIST item_response
	drop_down_style (true | false) "false"
	single_response (true | false) "true"
	select CDATA ""
>
<!-- The select attribute, if present, will be used to fill in selections for this item_response.
     The format is that of an SQL select statement.  The first select field will be used as the 
     strings displayed to the user.  The second field will be carried along invisibly with the 
     Selection objects as "extra information" (getExtraInfo()). -->
<!ELEMENT selection (question*)>
<!ATTLIST selection
	text CDATA #REQUIRED
	extra_info CDATA ""
	selected (true | false) "false"
	icon_img (true | false) "false"
	img_src CDATA ""
>
<!ELEMENT table_response (column_definitions, table_data*)>
<!ATTLIST table_response
	initial_rows_to_display CDATA "5"
	add_row_increment CDATA "3"
	row_height CDATA "1"
>
<!ELEMENT column_definitions (column_definition*)>
<!ELEMENT column_definition EMPTY>
<!ATTLIST column_definition
	label CDATA #REQUIRED
	width CDATA "0"
	pct CDATA "100"
>
<!ELEMENT table_data (cell*)>
<!ELEMENT cell (#PCDATA|question)*>
<!ATTLIST cell
	question_cell (true|false) "false"
>
<!ELEMENT material_list ((material | instruction)+)>
<!ELEMENT material EMPTY>
<!ATTLIST material
	id CDATA #REQUIRED
	description CDATA #IMPLIED
    internalOnly (true | false) "false"
	mandatory (true | false) "true"
>
<!ELEMENT instruction EMPTY>
<!ATTLIST instruction
	text CDATA #REQUIRED
>
<!ENTITY MONTH_YEAR_TABLE_RESPONSE SYSTEM "reusable/month_year_table_response.xml">
<!ENTITY SATISFACTION_ITEM_RESPONSE SYSTEM "reusable/satisfaction_item_response.xml">
<!ENTITY PAIN_ITEM_RESPONSE SYSTEM "reusable/pain_item_response.xml">
<!ENTITY MATERIAL_LIST_INTRODUCTORY_INSTRUCTION SYSTEM 
	"reusable/material_list_introductory_instruction.xml">
<!ENTITY MATERIAL_LIST_INTRODUCTORY_INSTRUCTION_ADOPTION SYSTEM 
	"reusable/material_list_introductory_instruction_adoption.xml">	
<!ENTITY MATERIAL_LIST_CLOSING_INSTRUCTION SYSTEM 
	"reusable/material_list_closing_instruction.xml">
<!ENTITY MATERIAL_LIST_CLOSING_INSTRUCTION_ADOPTION SYSTEM 
	"reusable/material_list_closing_instruction_adoption.xml">
<!ENTITY MATERIAL_LIST_CLOSING_INSTRUCTION_PLASTIC SYSTEM 
	"reusable/material_list_closing_instruction_plastic.xml">
<!ENTITY PHYSICIAN_LAST_REPORT SYSTEM 
	"reusable/physician_last_report.xml">
<!ENTITY PHYSICIAN_LAST_REPORT_PEDIATRIC SYSTEM 
	"reusable/physician_last_report_pediatric.xml">
<!ENTITY PAIN_SYSTEM_REVIEW SYSTEM 
	"reusable/pain_system_review.xml">
<!ENTITY SUBSTANCE_DEVELOPMENT_BACKGROUND SYSTEM 
	"reusable/substance_development_background.xml">
<!ENTITY PAIN_DISABILITY_INDEX SYSTEM 
	"reusable/pain_disability_index.xml">
<!ENTITY PLASTIC_COMMON1 SYSTEM 
	"reusable/plastic_common1.xml">
<!ENTITY PLASTIC_COMMON2 SYSTEM 
	"reusable/plastic_common2.xml">

=== mxu/ConditionEditor/app/data/Topol_RImmerman_Ruschhaupt_Bartholomew_LaPerna_Hyperlipidemia.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v3.5 (http://www.xmlspy.com) by David Hotchkiss (IT) -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "Topol_RImmerman_Ruschhaupt_Bartholomew_LaPerna_HyperlipidemiaMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "Topol_RImmerman_Ruschhaupt_Bartholomew_LaPerna_HyperlipidemiaQuestionnaire.xml">
]>
<division description="Cardiology" name="Cardiology">
	<department description="Cardiovascular Medicine" name="Cardiovascular Medicine">
		<section description="" name="">
			<!-- activated 02/17/09 per karen's request -->
			<condition active="true" cost="565.00" description="Hyperlipidemia" id="Hyperlipidemia">
				<keyword text="elevated"/>
				<keyword text="lipids"/>
				<keyword text="fats"/>
				<keyword text="circulation"/>
				<keyword text="heart"/>
				<keyword text="stroke"/>
				<keyword text="HDL"/>
				<keyword text="LDL"/>
				<keyword text="cholesterol"/>
				<keyword text="triglycerides"/>
				<keyword text="blood"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="565.00" description="Atheroembolism" id="Atheroembolism">
				<keyword text="fat"/>
				<keyword text="clot"/>
				<keyword text="circulation"/>
				<keyword text="heart"/>
				<keyword text="vascular"/>
				<keyword text="HDL"/>
				<keyword text="LDL"/>
				<keyword text="cholesterol"/>
				<keyword text="triglycerides"/>
				<keyword text="blood"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
		</section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/Henderson_PortalHypertension.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v3.5 (http://www.xmlspy.com) by David Hotchkiss (IT) -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "Henderson_PortalHypertensionMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "Henderson_PortalHypertensionQuestionnaire.xml">
]>
<division description="Surgery" name="Surgery">
	<department description="General Surgery" name="General Surgery">
		<section description="" name="">
			<condition cost="745.00" description="Portal Hypertension" id="Portal Hypertension" active="true">
				<keyword text="liver"/>
				<keyword text="hepatic"/>
				<keyword text="venous"/>
				<keyword text="blood flow"/>
				<keyword text="pressure"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
		</section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/Eckout_PseudocholinesteraseDeficiency.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Tony Hardee (Perot Systems) -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "Eckout_PseudocholinesteraseDeficiencyMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "Eckout_PseudocholinesteraseDeficiencyQuestionnaire.xml">
]>
<division description="Surgery" name="Surgery">
	<department description="Anesthesia" name="Anesthesia">
		<section description="" name="">
			<condition cost="565.00" description="Pseudocholinesterase Deficiency" id="Pseudocholinesterase Deficiency" active="true">
				<keyword text="anesthesia"/>
				<keyword text="anesthetic"/>
				<keyword text="anesthesiology"/>
				<keyword text="reaction"/>
				<keyword text="paralysis"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
		</section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/Schaffer_Krebs_KneeDisorders_NonTraumatic.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Tony Hardee (Perot Systems) -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "Schaffer_Krebs_KneeDisorders_NonTraumaticMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "Schaffer_Krebs_KneeDisorders_NonTraumaticQuestionnaire.xml">
]>
<division description="Surgery" name="Surgery">
	<department description="Orthopaedic Surgery" name="Orthopaedic Surgery">
		<section description="" name="">
			<condition cost="565.00" description="Bursitis (Knee)" id="Bursitis (Knee)">
				<keyword text="bursitis"/>
				<keyword text="inflammation"/>
				<keyword text="pain"/>
				<keyword text="joint"/>
				<keyword text="bursa"/>
				<keyword text="knee"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="565.00" description="Infected Knee" id="Infected Knee">
				<keyword text="infected"/>
				<keyword text="joint"/>
				<keyword text="knee"/>
				<keyword text="inflammation"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="565.00" description="Infected Knee Replacement" id="Infected Knee Replacement">
				<keyword text="infected"/>
				<keyword text="knee"/>
				<keyword text="prosthesis"/>
				<keyword text="degenerative"/>
				<keyword text="joint"/>
				<keyword text="inflammation"/>
				<keyword text="replacement"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="565.00" description="Osteoarthritis (Knee)" id="Osteoarthritis (Knee)">
				<keyword text="osteoarthritis"/>
				<keyword text="joint"/>
				<keyword text="knee"/>
				<keyword text="hip"/>
				<keyword text="degenerative"/>
				<keyword text="chronic"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="565.00" description="Knee Disorder (Non-Traumatic)" id="Knee Disorder (Non-Traumatic)">
				<keyword text="knee"/>
				<keyword text="disorder"/>
				<keyword text="joint"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
		</section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/Bell_Lieberman_Scoliosis.xml
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Tony Hardee (Perot Systems) -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "Bell_Lieberman_ScoliosisMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "Bell_Lieberman_ScoliosisQuestionnaire.xml">
]>
<division name="Surgery" description="Surgery">
	<department name="Spine Center" description="Spine Center">
		<section name="" description="">
      		<condition active="false" id="Scoliosis" description="Scoliosis" cost="565.00">
				<keyword text="back"/>
				<keyword text="spine"/>
				<keyword text="curvature"/>
				<keyword text="idiopathic"/>
				<keyword text="vertebrae"/>
				<keyword text="congenital"/>           
				&questionnaire_doc;
				&material_doc;	
			</condition>
			<condition id="Adult scoliosis (greater than 18 years)" description="Adult scoliosis (greater than 18 years)" cost="565.00">
				<keyword text="back"/>
				<keyword text="spine"/>
				<keyword text="curvature"/>
				&questionnaire_doc;
				&material_doc;	
			</condition>
			<condition id="Idiopathic scoliosis (4-18 years)" description="Idiopathic scoliosis (4-18 years)" cost="565.00">
				<keyword text="back"/>
				<keyword text="spine"/>
				<keyword text="curvature"/>
				<keyword text="pediatric"/>
				<keyword text="adolescent"/>
				&questionnaire_doc;
				&material_doc;	
			</condition>
			<condition id="Early onset scoliosis (less than 4 years)" description="Early onset scoliosis (less than 4 years)" cost="565.00">
				<keyword text="back"/>
				<keyword text="spine"/>
				<keyword text="curvature"/>
				<keyword text="pediatric"/>
				&questionnaire_doc;
				&material_doc;	
			</condition>
		</section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/Crowe_Lee_Moore_Budd_BreastCancer.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Tony Hardee (Perot Systems) -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "Crowe_Lee_Moore_Budd_BreastCancerMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "Crowe_Lee_Moore_Budd_BreastCancerQuestionnaire.xml">
]>
<division description="Surgery" name="Surgery">
	<department description="Hematology and Medical Oncology" name="Hematology and Medical Oncology">
		<section description="" name="">
			<condition cost="745.00" description="Breast Cancer (Medical Management Review)" id="Breast Cancer (Medical Management Review)">
				<keyword text="breast"/>
				<keyword text="cancer"/>
				<keyword text="malignant"/>
				<keyword text="carcinoma"/>
				<keyword text="tumor"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
		</section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/Hussein_Myeloma(Adult).xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- created with XML Spy v4.3 NT (http://www.xmlspy.com) by Harsha Reddy (ITD)-->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "Hussein_Myeloma(Adult)MaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "Hussein_Myeloma(Adult)Questionnaire.xml">
]>
<division description="Cancer Center" name="Cancer Center">
	<department description="Hematology and Medical Oncology" name="Hematology and Medical Oncology">
		<section description="" name="">
			<condition cost="745.00" description="MGUS (adult)" id="MGUS (adult)" active="true">
				<keyword text="myeloma"/>
				<keyword text="cancer"/>
				<keyword text="malignant"/>
				<keyword text="malignancy"/>
				<keyword text="tumor"/>
				<keyword text="carcinoma"/>
				<keyword text="bone"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Monoclonal Protein (adult)" id="Monoclonal Protein (adult)" active="true">
				<keyword text="myeloma"/>
				<keyword text="cancer"/>
				<keyword text="malignant"/>
				<keyword text="malignancy"/>
				<keyword text="tumor"/>
				<keyword text="carcinoma"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Multiple Myeloma (adult)" id="Multiple Myeloma (adult)" active="true">
				<keyword text="cancer"/>
				<keyword text="malignant"/>
				<keyword text="malignancy"/>
				<keyword text="tumor"/>
				<keyword text="carcinoma"/>
				<keyword text="bone"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Plasma Cell Dysplasia (adult)" id="Plasma Cell Dysplasia (adult)" active="true">
				<keyword text="cancer"/>
				<keyword text="malignant"/>
				<keyword text="malignancy"/>
				<keyword text="tumor"/>
				<keyword text="carcinoma"/>
				<keyword text="bone"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Plasmacytoma (adult)" id="Plasmacytoma (adult)" active="true">
				<keyword text="myeloma"/>
				<keyword text="cancer"/>
				<keyword text="malignant"/>
				<keyword text="malignancy"/>
				<keyword text="tumor"/>
				<keyword text="carcinoma"/>
				<keyword text="bone"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="POEMS Syndrome (adult)" id="POEMS Syndrome (adult)" active="true">
				<keyword text="myeloma"/>
				<keyword text="cancer"/>
				<keyword text="malignant"/>
				<keyword text="malignancy"/>
				<keyword text="tumor"/>
				<keyword text="carcinoma"/>
				<keyword text="bone"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Myeloma (adult)" id="Myeloma (adult)" active="true">
				<keyword text="multiple"/>
				<keyword text="cancer"/>
				<keyword text="malignant"/>
				<keyword text="malignancy"/>
				<keyword text="tumor"/>
				<keyword text="carcinoma"/>
				<keyword text="bone"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
		</section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/Wyllie_Liver_Disease(pediatric).xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by David Hotchkiss (IT) -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "Wyllie_Liver_Disease(pediatric)MaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "Wyllie_Liver_Disease(pediatric)Questionnaire.xml">
]>
<division description="Surgery" name="Surgery">
	<department description="Pediatric Gastroenterology" name="Pediatric Gastroenterology">
		<section description="" name="">
			<condition cost="745.00" description="Chronic Viral Hepatitis (pediatric)" id="Chronic Viral Hepatitis (pediatric)">
				<keyword text="liver"/>
				<keyword text="virus"/>
				<keyword text="hepatic"/>
				<keyword text="gastrointestinal"/>
				<keyword text="GI"/>
				<keyword text="inflammation"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Autoimmune Hepatitis (pediatric)" id="Autoimmune Hepatitis (pediatric)">
				<keyword text="liver"/>
				<keyword text="infection"/>
				<keyword text="hepatic"/>
				<keyword text="gastrointestinal"/>
				<keyword text="GI"/>
				<keyword text="inflammation"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
		</section>
	</department>
</division>
