=== mxu/ConditionEditor/app/data/condition.dtd
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Tony Hardee (Perot Systems) -->
<!ENTITY % response "(free_form_response|item_response|table_response)?">
<!ENTITY % restriced_service "(restricted_state|restricted_country)">
<!ENTITY % physician_ref "(physician_id|physician)">
<!ELEMENT divisions (division+)>
<!ELEMENT division (department+)>
<!ATTLIST division
	name CDATA #REQUIRED
	description CDATA #REQUIRED
>
<!ELEMENT department (section+)>
<!ATTLIST department
	name CDATA #REQUIRED
	description CDATA #REQUIRED
>
<!ELEMENT section (condition+)>
<!ATTLIST section
	name CDATA #REQUIRED
	description CDATA #REQUIRED
>
<!ELEMENT condition (keyword*, questionnaire, material_list)>
<!ATTLIST condition
	id CDATA #REQUIRED
	active (true | false) "true"
	cost CDATA #REQUIRED
	description CDATA #REQUIRED
	product_id CDATA #IMPLIED
>
<!ELEMENT keyword EMPTY>
<!ATTLIST keyword
	text CDATA #REQUIRED
>
<!ELEMENT questionnaire (question_group+)>
<!ELEMENT question_group (question+)>
<!ATTLIST question_group
	name CDATA #REQUIRED
>
<!ELEMENT question (%response;)>
<!ATTLIST question
	prompt CDATA #REQUIRED
	id CDATA #IMPLIED
	callout CDATA #IMPLIED
	mandatory (true | false) "true"
>
<!ELEMENT free_form_response EMPTY>
<!ATTLIST free_form_response
	response CDATA #IMPLIED
	height CDATA "1"
	width CDATA "80"
>

<!ELEMENT item_response (selection*)>
<!ATTLIST item_response
	drop_down_style (true | false) "false"
	single_response (true | false) "true"
	select CDATA ""
>
<!-- The select attribute, if present, will be used to fill in selections for this item_response.
     The format is that of an SQL select statement.  The first select field will be used as the 
     strings displayed to the user.  The second field will be carried along invisibly with the 
     Selection objects as "extra information" (getExtraInfo()). -->
<!ELEMENT selection (question*)>
<!ATTLIST selection
	text CDATA #REQUIRED
	extra_info CDATA ""
	selected (true | false) "false"
	icon_img (true | false) "false"
	img_src CDATA ""
>
<!ELEMENT table_response (column_definitions, table_data*)>
<!ATTLIST table_response
	initial_rows_to_display CDATA "5"
	add_row_increment CDATA "3"
	row_height CDATA "1"
>
<!ELEMENT column_definitions (column_definition*)>
<!ELEMENT column_definition EMPTY>
<!ATTLIST column_definition
	label CDATA #REQUIRED
	width CDATA "0"
	pct CDATA "100"
>
<!ELEMENT table_data (cell*)>
<!ELEMENT cell (#PCDATA|question)*>
<!ATTLIST cell
	question_cell (true|false) "false"
>
<!ELEMENT material_list ((material | instruction)+)>
<!ELEMENT material EMPTY>
<!ATTLIST material
	id CDATA #REQUIRED
	description CDATA #IMPLIED
    internalOnly (true | false) "false"
	mandatory (true | false) "true"
>
<!ELEMENT instruction EMPTY>
<!ATTLIST instruction
	text CDATA #REQUIRED
>
<!ENTITY MONTH_YEAR_TABLE_RESPONSE SYSTEM "reusable/month_year_table_response.xml">
<!ENTITY SATISFACTION_ITEM_RESPONSE SYSTEM "reusable/satisfaction_item_response.xml">
<!ENTITY PAIN_ITEM_RESPONSE SYSTEM "reusable/pain_item_response.xml">
<!ENTITY MATERIAL_LIST_INTRODUCTORY_INSTRUCTION SYSTEM 
	"reusable/material_list_introductory_instruction.xml">
<!ENTITY MATERIAL_LIST_INTRODUCTORY_INSTRUCTION_ADOPTION SYSTEM 
	"reusable/material_list_introductory_instruction_adoption.xml">	
<!ENTITY MATERIAL_LIST_CLOSING_INSTRUCTION SYSTEM 
	"reusable/material_list_closing_instruction.xml">
<!ENTITY MATERIAL_LIST_CLOSING_INSTRUCTION_ADOPTION SYSTEM 
	"reusable/material_list_closing_instruction_adoption.xml">
<!ENTITY MATERIAL_LIST_CLOSING_INSTRUCTION_PLASTIC SYSTEM 
	"reusable/material_list_closing_instruction_plastic.xml">
<!ENTITY PHYSICIAN_LAST_REPORT SYSTEM 
	"reusable/physician_last_report.xml">
<!ENTITY PHYSICIAN_LAST_REPORT_PEDIATRIC SYSTEM 
	"reusable/physician_last_report_pediatric.xml">
<!ENTITY PAIN_SYSTEM_REVIEW SYSTEM 
	"reusable/pain_system_review.xml">
<!ENTITY SUBSTANCE_DEVELOPMENT_BACKGROUND SYSTEM 
	"reusable/substance_development_background.xml">
<!ENTITY PAIN_DISABILITY_INDEX SYSTEM 
	"reusable/pain_disability_index.xml">
<!ENTITY PLASTIC_COMMON1 SYSTEM 
	"reusable/plastic_common1.xml">
<!ENTITY PLASTIC_COMMON2 SYSTEM 
	"reusable/plastic_common2.xml">

=== mxu/ConditionEditor/app/data/Deitcher_Lichtin_Thrombocythemia_Thrombocytosis.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v4.2 (http://www.xmlspy.com) by David Hotchkiss (IT) -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "Deitcher_Lichtin_Thrombocythemia_ThrombocytosisMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "Deitcher_Lichtin_Thrombocythemia_ThrombocytosisQuestionnaire.xml">
]>
<division description="Surgery" name="Surgery">
	<department description="Hematology and Medical Oncology" name="Hematology and Medical Oncology">
		<section description="" name="">
			<condition active="true" cost="745.00" description="Thrombocythemia" id="Thrombocythemia">
				<keyword text="elevated"/>
				<keyword text="platelet"/>
				<keyword text="count"/>
				<keyword text="disorder"/>
				<keyword text="hematology"/>
				<keyword text="blood"/>
				<keyword text="myeloproliferative"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition active="true" cost="745.00" description="Primary (Essential) Thrombocythemia" id="Primary (Essential) Thrombocythemia">
				<keyword text="platelet"/>
				<keyword text="blood"/>
				<keyword text="myeloproliferative"/>		
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition active="true" cost="745.00" description="Secondary Thrombocythemia" id="Secondary Thrombocythemia">
				<keyword text="elevated"/>
				<keyword text="platelet"/>
				<keyword text="count"/>
				<keyword text="disorder"/>
				<keyword text="hematology"/>
				<keyword text="myeloproliferative"/>
				<keyword text="blood"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition active="true" cost="745.00" description="Thrombocytosis" id="Thrombocytosis">
				<keyword text="myeloproliferative"/>
				<keyword text="platelet"/>
				<keyword text="blood"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition active="true" cost="745.00" description="Primary (Essential) Thrombocytosis" id="Primary (Essential) Thrombocytosis">
				<keyword text="platelet"/>
				<keyword text="myeloproliferative"/>
				<keyword text="blood"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition active="true" cost="745.00" description="Secondary Thrombocytosis" id="Secondary Thrombocytosis">
				<keyword text="platelet"/>
				<keyword text="myeloproliferative"/>
				<keyword text="blood"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
		</section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/Rackley_StressIncontinence(male).xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Penny Black -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "Rackley_StressIncontinence(male)MaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "Rackley_StressIncontinence(male)Questionnaire.xml">
]>
<division description="Surgery" name="Surgery">
	<department description="Urology" name="Urology">
		<section description="" name="">
			<condition cost="745.00" description="Stress Incontinence (male)" id="Stress Incontinence (male)" active="true">
				<keyword text="incontinent"/>
				<keyword text="urine"/>
				<keyword text="urological"/>
				<keyword text="bladder"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Urinary Incontinence (male)" id="Urinary Incontinence (male)" active="true">
				<keyword text="incontinent"/>
				<keyword text="urine"/>
				<keyword text="urological"/>
				<keyword text="bladder"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="565.00" description="Neurogenic Bladder (male)" id="Neurogenic Bladder (male)" active="true">
				<keyword text="hypotonic"/>
				<keyword text="flaccid"/>
				<keyword text="spastic"/>
				<keyword text="contracted"/>
				<keyword text="urinary"/>
				<keyword text="dysfunction"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Neurogenic Bladder (male) (with Pathology)" id="Neurogenic Bladder (male) (with Pathology)" active="true">
				<keyword text="hypotonic"/>
				<keyword text="flaccid"/>
				<keyword text="spastic"/>
				<keyword text="contracted"/>
				<keyword text="urinary"/>
				<keyword text="dysfunction"/>
				&questionnaire_doc;
				&material_doc;
			</condition>			
		</section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/Klein_Dreicer_TesticularCa.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v4.2 (http://www.xmlspy.com) by Penny Black (IT) -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "Klein_Dreicer_TesticularCaMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "Klein_Dreicer_TesticularCaQuestionnaire.xml">
]>
<division description="Surgery" name="Surgery">
	<department description="Hematology and Medical Oncology" name="Hematology and Medical Oncology">
		<section description="" name="">
			<condition cost="745.00" description="Testicular Cancer" id="Testicular Cancer">
				<keyword text="Testicular"/>
				<keyword text="Cancer"/>
				<keyword text="Malignant"/>
				<keyword text="Carcinoma"/>
				<keyword text="Tumor"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
		</section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/Wyllie_Esophageal_Disorders.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Tony Hardee (Perot Systems) -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "Wyllie_Esophageal_DisordersMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "Wyllie_Esophageal_DisordersQuestionnaire.xml">
]>
<division description="Surgery" name="Surgery">
	<department description="Pediatric Gastroenterology" name="Pediatric Gastroenterology">
		<section description="" name="">
			<condition cost="745.00" description="Achalasia (pediatric)" id="Achalasia (pediatric)" active="true">
				<keyword text="malabsorption"/>
				<keyword text="bowel"/>
				<keyword text="intestines"/>
				<keyword text="gastrointestinal"/>
				<keyword text="GI"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Esophageal Sphincter Dysfunction (pediatric)" id="Esophageal Sphincter Dysfunction (pediatric)" active="true">
				<keyword text="malabsorption"/>
				<keyword text="bowel"/>
				<keyword text="intestines"/>
				<keyword text="gastrointestinal"/>
				<keyword text="GI"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Esophageal Spasm (pediatric)" id="Esophageal Spasm (pediatric)" active="true">
				<keyword text="malabsorption"/>
				<keyword text="bowel"/>
				<keyword text="intestines"/>
				<keyword text="gastrointestinal"/>
				<keyword text="GI"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Esophageal Diverticula (pediatric)" id="Esophageal Diverticula (pediatric)" active="true">
				<keyword text="malabsorption"/>
				<keyword text="bowel"/>
				<keyword text="intestines"/>
				<keyword text="gastrointestinal"/>
				<keyword text="GI"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
		</section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/Schaffer_Krebs_AnkylosingSpondylitis.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Tony Hardee (Perot Systems) -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "Schaffer_Krebs_AnkylosingSpondylitisMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "Schaffer_Krebs_AnkylosingSpondylitisQuestionnaire.xml">
]>
<division description="Surgery" name="Surgery">
	<department description="Spine Center" name="Spine Center">
		<section description="" name="">
			<condition active="true" cost="565.00" description="Ankylosing spondylitis of the knee" id="Ankylosing spondylitis of the knee">
				<keyword text="joint "/>
				<keyword text="degenerative"/>
				<keyword text="chronic"/>
				<keyword text="acetabulum"/>	
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition active="true" cost="565.00" description="Ankylosing spondylitis of the hip" id="Ankylosing spondylitis of the hip">
				<keyword text="joint "/>
				<keyword text="degenerative"/>
				<keyword text="chronic"/>
				<keyword text="acetabulum"/>			
				&questionnaire_doc;
				&material_doc;
			</condition>
			<!-- inactivated 2/3/05 Per Sharon Plona's request -->
			<!-- moved to Gota_RheumatoidArthritis.xml to change to department 
			<condition active="false" cost="565.00" description="Rheumatoid Arthritis" id="Rheumatoid Arthritis">
				<keyword text="joint "/>
				<keyword text="degenerative"/>
				<keyword text="chronic"/>
				<keyword text="autoimmune"/>
				<keyword text="RA"/>					
				&questionnaire_doc;
				&material_doc;
			</condition> -->
         <!-- inactivated 2/3/05 Per Sharon Plona's request 
			<condition active="false" cost="565.00" description="Juvenile Rheumatoid Arthritis" id="Juvenile Rheumatoid Arthritis">
				<keyword text="joint "/>
				<keyword text="degenerative"/>
				<keyword text="autoimmune"/>
				<keyword text="JRA"/>	
				&questionnaire_doc;
				&material_doc;
			</condition> -->

		</section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/MaleInfertility.xml
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v3.5 (http://www.xmlspy.com) by Harsha Reddy(IT) -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "MaleInfertilityMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "MaleInfertilityQuestionnaire.xml">
]>
<division description="Surgery" name="Surgery">
	<department description="Urology" name="Glickman Kidney and Urological Institute">
		<section description="" name="">
			<condition cost="745.00" description="Infertility (Male)" id="Infertility (Male)" active="true">
				<keyword text="Male"/>
				<keyword text="Infertility"/>
				<keyword text="Sperm"/>
				<keyword text="Semen"/>
				<keyword text="Baby"/>
				<keyword text="Conception"/>
				<keyword text="Conceive"/>
				<keyword text="Pregnancy"/>
				<keyword text="testosterone"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
		</section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/Mayberg_PituitaryTumor.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Tony Hardee (Perot Systems) -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "Mayberg_PituitaryTumorMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "Mayberg_PituitaryTumorQuestionnaire.xml">
]>
<!-- Added vogelbaum & barnett to the file per Sharon Plona's VM request 11/12/03 DCH -->
<division description="Surgery" name="Surgery">
	<department description="Neurological Surgery" name="Neurological Surgery">
		<section description="" name="">
			<condition active="true" cost="745.00" description="Acoustic Neuroma (neurosurgical evaluation)" id="Acoustic Neuroma (neurosurgical evaluation)">
				<keyword text="schwannomas"/>
				<keyword text="tumor"/>
				<keyword text="neoplasm"/>
				<keyword text="ear"/>
				<keyword text="mass"/>
				<keyword text="growth"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition active="true" cost="745.00" description="Acromegaly (as a result of pituitary tumor)" id="Acromegaly (as a result of pituitary tumor)">
				<keyword text="hyperpituitarism"/>
				<keyword text="giantism"/>
				<keyword text="neoplasm"/>
				<keyword text="mass"/>
				<keyword text="growth"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition active="true" cost="745.00" description="Craniopharyngioma" id="Craniopharyngioma">
				<keyword text="tumor"/>
				<keyword text="pituitary"/>
				<keyword text="hypothalamus"/>
				<keyword text="mass"/>
				<keyword text="benign"/>
				<keyword text="neoplasm"/>
				<keyword text="growth"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition active="true" cost="745.00" description="Cushing's Disease (as a result of Pituitary Tumor)" id="Cushing's Disease (as a result of Pituitary Tumor)">
				<keyword text="gland"/>
				<keyword text="cortisol"/>
				<keyword text="hypercortisolemia"/>
				<keyword text="adenoma"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition active="true" cost="745.00" description="Pituitary Tumor (adult)" id="Pituitary Tumor (adult)">
				<keyword text="gland"/>
				<keyword text="benign"/>
				<keyword text="neoplasm"/>
				<keyword text="mass"/>
				<keyword text="growth"/>
				<keyword text="malignant"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition active="true" cost="745.00" description="Prolactinoma" id="Prolactinoma">
				<keyword text="pituitary"/>
				<keyword text="gland"/>
				<keyword text="tumor"/>
				<keyword text="mass"/>
				<keyword text="neoplasm"/>
				<keyword text="benign"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition active="true" cost="745.00" description="Hypopituitarism" id="Hypopituitarism">
				<keyword text="pituitary"/>
				<keyword text="gland"/>
				<keyword text="hypopituitarism"/>
				<keyword text="decreased"/>
				<keyword text="secretion"/>
				<keyword text="condition"/>
				<keyword text="hormone"/>
				<keyword text="disorder"/>
				<keyword text="hormones"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition active="true" cost="745.00" description="Growth hormone deficiency" id="Growth hormone deficiency">
				<keyword text="growth"/>
				<keyword text="hormone"/>
				<keyword text="deficiency"/>
				<keyword text="GHD"/>
				<keyword text="conditions"/>
				<keyword text="production"/>
				<keyword text="decreased"/>
				<keyword text="pituitary"/>
				<keyword text="gland"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition active="true" cost="745.00" description="Hypogonadism" id="Hypogonadism">
				<keyword text="gland"/>
				<keyword text="sex"/>
				<keyword text="decreased"/>
				<keyword text="hormone"/>
				<keyword text="gonads"/>
				<keyword text="testes"/>
				<keyword text="function"/>
				<keyword text="testosterone"/>
				<keyword text="deficiency"/>
				<keyword text="adrogen"/>
				<keyword text="sperm"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
		</section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/Fazio_Sengore_Church_PelvicPouchProblems.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v3.5 (http://www.xmlspy.com) by David Hotchkiss (IT) -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "Fazio_Sengore_Church_PelvicPouchProblemsMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "Fazio_Sengore_Church_PelvicPouchProblemsQuestionnaire.xml">
]>
<!--02/14/02 Kewords removed per Linda Vrabel to allow for clean-up prior to release to production.  DH-->
<division description="Surgery" name="Surgery">
	<department description="Colorectal Surgery" name="Colorectal Surgery">
		<section description="" name="">
			<condition cost="745.00" description="Pelvic Pouch Problems" id="Pelvic Pouch Problems">
				<keyword text="pelvic pouch"/>
				<keyword text="pouch problems"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Pelvic Pouchitis" id="Pelvic Pouchitis">
				<keyword text="colostomy"/>
				<keyword text="pouch"/>
				<keyword text="crohn's"/>
				<keyword text="colitis"/>
				<keyword text="bowel"/>
				<keyword text="intestine"/>
				<keyword text="colon"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Pelvic Pouch Malfunction" id="Pelvic Pouch Malfunction">
				<keyword text="crohn's"/>
				<keyword text="colitis"/>
				<keyword text="intestine"/>
				<keyword text="colon"/>
				<keyword text="colostomy"/>
				<keyword text="bowel"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Pelvic Pouch Abscess" id="Pelvic Pouch Abscess">
				<keyword text="pelvic abscess"/>
				<keyword text="bowel"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
		</section>
	</department>
</division>
