=== mxu/ConditionEditor/app/data/condition.dtd
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Tony Hardee (Perot Systems) -->
<!ENTITY % response "(free_form_response|item_response|table_response)?">
<!ENTITY % restriced_service "(restricted_state|restricted_country)">
<!ENTITY % physician_ref "(physician_id|physician)">
<!ELEMENT divisions (division+)>
<!ELEMENT division (department+)>
<!ATTLIST division
	name CDATA #REQUIRED
	description CDATA #REQUIRED
>
<!ELEMENT department (section+)>
<!ATTLIST department
	name CDATA #REQUIRED
	description CDATA #REQUIRED
>
<!ELEMENT section (condition+)>
<!ATTLIST section
	name CDATA #REQUIRED
	description CDATA #REQUIRED
>
<!ELEMENT condition (keyword*, questionnaire, material_list)>
<!ATTLIST condition
	id CDATA #REQUIRED
	active (true | false) "true"
	cost CDATA #REQUIRED
	description CDATA #REQUIRED
	product_id CDATA #IMPLIED
>
<!ELEMENT keyword EMPTY>
<!ATTLIST keyword
	text CDATA #REQUIRED
>
<!ELEMENT questionnaire (question_group+)>
<!ELEMENT question_group (question+)>
<!ATTLIST question_group
	name CDATA #REQUIRED
>
<!ELEMENT question (%response;)>
<!ATTLIST question
	prompt CDATA #REQUIRED
	id CDATA #IMPLIED
	callout CDATA #IMPLIED
	mandatory (true | false) "true"
>
<!ELEMENT free_form_response EMPTY>
<!ATTLIST free_form_response
	response CDATA #IMPLIED
	height CDATA "1"
	width CDATA "80"
>

<!ELEMENT item_response (selection*)>
<!ATTLIST item_response
	drop_down_style (true | false) "false"
	single_response (true | false) "true"
	select CDATA ""
>
<!-- The select attribute, if present, will be used to fill in selections for this item_response.
     The format is that of an SQL select statement.  The first select field will be used as the 
     strings displayed to the user.  The second field will be carried along invisibly with the 
     Selection objects as "extra information" (getExtraInfo()). -->
<!ELEMENT selection (question*)>
<!ATTLIST selection
	text CDATA #REQUIRED
	extra_info CDATA ""
	selected (true | false) "false"
	icon_img (true | false) "false"
	img_src CDATA ""
>
<!ELEMENT table_response (column_definitions, table_data*)>
<!ATTLIST table_response
	initial_rows_to_display CDATA "5"
	add_row_increment CDATA "3"
	row_height CDATA "1"
>
<!ELEMENT column_definitions (column_definition*)>
<!ELEMENT column_definition EMPTY>
<!ATTLIST column_definition
	label CDATA #REQUIRED
	width CDATA "0"
	pct CDATA "100"
>
<!ELEMENT table_data (cell*)>
<!ELEMENT cell (#PCDATA|question)*>
<!ATTLIST cell
	question_cell (true|false) "false"
>
<!ELEMENT material_list ((material | instruction)+)>
<!ELEMENT material EMPTY>
<!ATTLIST material
	id CDATA #REQUIRED
	description CDATA #IMPLIED
    internalOnly (true | false) "false"
	mandatory (true | false) "true"
>
<!ELEMENT instruction EMPTY>
<!ATTLIST instruction
	text CDATA #REQUIRED
>
<!ENTITY MONTH_YEAR_TABLE_RESPONSE SYSTEM "reusable/month_year_table_response.xml">
<!ENTITY SATISFACTION_ITEM_RESPONSE SYSTEM "reusable/satisfaction_item_response.xml">
<!ENTITY PAIN_ITEM_RESPONSE SYSTEM "reusable/pain_item_response.xml">
<!ENTITY MATERIAL_LIST_INTRODUCTORY_INSTRUCTION SYSTEM 
	"reusable/material_list_introductory_instruction.xml">
<!ENTITY MATERIAL_LIST_INTRODUCTORY_INSTRUCTION_ADOPTION SYSTEM 
	"reusable/material_list_introductory_instruction_adoption.xml">	
<!ENTITY MATERIAL_LIST_CLOSING_INSTRUCTION SYSTEM 
	"reusable/material_list_closing_instruction.xml">
<!ENTITY MATERIAL_LIST_CLOSING_INSTRUCTION_ADOPTION SYSTEM 
	"reusable/material_list_closing_instruction_adoption.xml">
<!ENTITY MATERIAL_LIST_CLOSING_INSTRUCTION_PLASTIC SYSTEM 
	"reusable/material_list_closing_instruction_plastic.xml">
<!ENTITY PHYSICIAN_LAST_REPORT SYSTEM 
	"reusable/physician_last_report.xml">
<!ENTITY PHYSICIAN_LAST_REPORT_PEDIATRIC SYSTEM 
	"reusable/physician_last_report_pediatric.xml">
<!ENTITY PAIN_SYSTEM_REVIEW SYSTEM 
	"reusable/pain_system_review.xml">
<!ENTITY SUBSTANCE_DEVELOPMENT_BACKGROUND SYSTEM 
	"reusable/substance_development_background.xml">
<!ENTITY PAIN_DISABILITY_INDEX SYSTEM 
	"reusable/pain_disability_index.xml">
<!ENTITY PLASTIC_COMMON1 SYSTEM 
	"reusable/plastic_common1.xml">
<!ENTITY PLASTIC_COMMON2 SYSTEM 
	"reusable/plastic_common2.xml">

=== mxu/ConditionEditor/app/data/Decamp_Esophagealcancer.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Tony Hardee (Perot Systems) -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "Decamp_EsophagealcancerMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "Decamp_EsophagealcancerQuestionnaire.xml">
]>
<division description="Surgery" name="Surgery">
	<department description="Thoracic and Cardiovascular Surgery" name="Thoracic and Cardiovascular Surgery">
		<section description="" name="">
			<condition cost="745.00" description="Esophageal Cancer" id="Esophageal Cancer">
				<keyword text="esophageal"/>
				<keyword text="cancer"/>
				<keyword text="carcinoma"/>
				<keyword text="tumor"/>
				<keyword text="malignant"/>
				<keyword text="gastrointestinal"/>
				<keyword text="malignancy"/>
				<keyword text="Ca"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
		</section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/FibromuscularDysplasia.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "FibromuscularDysplasiaMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "Fibromuscular_DysplasiaQuestionnaire.xml">
	
]>
<division description="Cardiology" name="Cardiology">
	<department description="Cardiovascular Medicine" name="Cardiovascular Medicine">
		<section description="" name="">
			<condition cost="565.00" description="Fibromuscular Dysplasia" id="Fibromuscular Dysplasia">
				<keyword text="dysplasia"/>
				<keyword text="abnormal"/>
				<keyword text="artery"/>
				<keyword text="arteries"/>
				<keyword text="walls"/>
				<keyword text="narrowing"/>
				<keyword text="stenosis"/>
				<keyword text="cell"/>
				<keyword text="carotid"/>
				<keyword text="renal"/>
				<keyword text="FMD"/>
				<keyword text="neck"/>
				<keyword text="kidney"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="565.00" description="Carotid Dissection" id="Carotid Dissection">
				<keyword text="dysplasia"/>
				<keyword text="abnormal"/>
				<keyword text="artery"/>
				<keyword text="arteries"/>
				<keyword text="walls"/>
				<keyword text="narrowing"/>
				<keyword text="stenosis"/>
				<keyword text="cell"/>
				<keyword text="carotid"/>
				<keyword text="renal"/>
				<keyword text="FMD"/>
				<keyword text="neck"/>
				<keyword text="kidney"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
		</section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/SleepDisorders.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Tony Hardee (Perot Systems) -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "SleepDisordersMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "SleepDisordersQuestionnaire.xml">
]>
<division description="General Medicine" name="General Medicine">
	<department description="Neurology" name="Neurology">
		<section description="" name="">
			<condition cost="565.00" description="Sleep Disorders" id="Sleep Disorders">
				<keyword text="sleep"/>
				<keyword text="disorder"/>
				<keyword text="insomnia"/>
				<keyword text="fatigue"/>
				<keyword text="chronic"/>
				<keyword text="snoring"/>
				<keyword text="apnea"/>

				&questionnaire_doc;
				&material_doc;
			</condition>
		</section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/Sinusitis.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Tony Hardee (Perot Systems) -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "SinusitisMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "SinusitisQuestionnaire.xml">
]>
<division description="Surgery" name="Surgery">
	<department description="Otolaryngology" name="Otolaryngology">
		<section description="" name="">
			<condition cost="745.00" description="Sinusitis" id="Sinusitis">
				<keyword text="sinus"/>
				<keyword text="nose"/>
				<keyword text="nasal"/>
				<keyword text="infection"/>
				<keyword text="blockage"/>
				<keyword text="paranasal"/>
				<keyword text="inflammation"/>
				<keyword text="infected"/>
				<keyword text="inflamed"/>
				<keyword text="rhinosinusitis"/>
				<keyword text="rhinitis"/>
				<keyword text="deviated"/>
				<keyword text="septum"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Deviated Septum" id="Deviated Septum">
				<keyword text="sinus"/>
				<keyword text="nose"/>
				<keyword text="nasal"/>
				<keyword text="infection"/>
				<keyword text="blockage"/>
				<keyword text="paranasal"/>
				<keyword text="inflammation"/>
				<keyword text="infected"/>
				<keyword text="inflamed"/>
				<keyword text="rhinosinusitis"/>
				<keyword text="rhinitis"/>
				<keyword text="deviated"/>
				<keyword text="septum"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
		</section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/LungCancer.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Tony Hardee (Perot Systems) -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "LungCancerMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "LungCancerQuestionnaire.xml">
]>
<division description="Surgery" name="Surgery">
	<department description="Pulmonary Medicine" name="Pulmonary Medicine">
		<section description="" name="">
			<condition cost="745.00" description="Bronchogenic Carcinoma" id="Bronchogenic Carcinoma">
				<keyword text="lung"/>
				<keyword text="cancer"/>
				<keyword text="tumor"/>
				<keyword text="pulmonary"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Lung Cancer" id="Lung Cancer">
				<keyword text="disease"/>
				<keyword text="tumor"/>
				<keyword text="nodule"/>
				<keyword text="pulmonary"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Lung Nodule" id="Lung Nodule">
				<keyword text="cancer"/>
				<keyword text="disorder"/>
				<keyword text="pulmonary disorder"/>
				<keyword text="tumor"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Metastatic Lung Cancer" id="Metastatic Lung Cancer">
				<keyword text="carcinoma"/>
				<keyword text="malignancy"/>
				<keyword text="malignant"/>
				<keyword text="metastasis"/>
				<keyword text="pulmonary"/>
				<keyword text="spread"/>
				<keyword text="tumor"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
		</section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/Bell_Lieberman_SpinalInfection.xml
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Tony Hardee (Perot Systems) -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "Bell_Lieberman_SpinalInfectionMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "Bell_Lieberman_SpinalInfectionQuestionnaire.xml">
]>
<division name="Surgery" description="Surgery">
	<department name="Spine Center" description="Spine Center">
		<section name="" description="">
			<condition id="Discitis" description="Discitis" cost="745.00">
				<keyword text="back"/>
				<keyword text="disc"/>
				<keyword text="bone"/>
				<keyword text="spinal"/>
				<keyword text="spine"/>
				<keyword text="orthopaedic"/>
				<keyword text="orthopedic"/>
				<keyword text="infection"/>	
				&questionnaire_doc;
				&material_doc;	
			</condition>
			<condition id="Disc Space Infection" description="Disc Space Infection" cost="745.00">
				<keyword text="spinal"/>
				<keyword text="spine"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition id="Spinal Abscess" description="Spinal Abscess" cost="745.00">
				<keyword text="back"/>
				<keyword text="abscess"/>
				<keyword text="bone"/>
				<keyword text="spinal"/>
				<keyword text="spine"/>
				<keyword text="vertebral"/>
				<keyword text="orthopaedic"/>
				<keyword text="orthopedic"/>
				<keyword text="infection"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
         <condition id="Vertebral Osteomyelitis" description="Vertebral Osteomyelitis" cost="745.00">
            <keyword text="bone"/>
            <keyword text="infection"/>
            <keyword text="vertebrae"/>
            <keyword text="bacterial"/>
            <keyword text="viral"/>
            <keyword text="bacteria"/>
            <keyword text="virus"/>
            &questionnaire_doc;
				&material_doc;
			</condition>
		</section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/IntestinalTransplant.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "IntestinalTransplantMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "IntestinalTransplantQuestionnaire.xml">
]>
<division description="Digestive Disease" name="Digestive Disease">
	<department description="Transplant" name="Transplant">
		<section description="" name="">
			<condition cost="745.00" description="Intestinal Rehab and Transplant (Adults 18 and over)" id="Intestinal Rehab and Transplant (Adults 18 and over)" active="true">
				<keyword text="intestine"/>
				<keyword text="intestinal"/>
				<keyword text="transplant"/>
				<keyword text="gastrointestinal"/>
				<keyword text="GI"/>
				<keyword text="failure"/>
				<keyword text="short"/>
				<keyword text="bowel"/>
				<keyword text="syndrome"/>
				<keyword text="rehabilitation"/>
				<keyword text="gut"/>
				<keyword text="rehab"/>
				<keyword text="disease"/>
				<keyword text="resection"/>
				<keyword text="crohn's"/>
				<keyword text="colitis"/>
				<keyword text="malabsorption"/>
				<keyword text="TPN"/>
				<keyword text="total"/>
				<keyword text="parenteral"/>
				<keyword text="nutrition"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
        </section>
	</department>
</division>

=== mxu/ConditionEditor/app/data/Siperstein_Strome_ThyroidCancer.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../condition.xsl"?>
<!-- edited with XML Spy v4.2 (http://www.xmlspy.com) by Penny Black (IT) -->
<!DOCTYPE division SYSTEM "condition.dtd" [
	<!ENTITY material_doc SYSTEM "Siperstein_Strome_ThyroidCancerMaterialList.xml">
	<!ENTITY questionnaire_doc SYSTEM "Siperstein_Strome_ThyroidCancerQuestionnaire.xml">
]>
<division description="Surgery" name="Surgery">
	<department description="Otolaryngology" name="Otolaryngology">
		<section description="" name="">
			<condition cost="745.00" description="Thyroid Mass" id="Thyroid Mass">
				<keyword text="tumor"/>
				<keyword text="thyroid"/>
				<keyword text="mass"/>
				<keyword text="gland"/>
				<keyword text="endocrine"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Hurthle Cell Cancer" id="Hurthle Cell Cancer">
				<keyword text="cancer"/>
				<keyword text="thyroid"/>
				<keyword text="carcinoma"/>
				<keyword text="tumor"/>
				<keyword text="gland"/>
				<keyword text="endocrine"/>
				<keyword text="Hurthle"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Medullary Cancer" id="Medullary Cancer">
				<keyword text="cancer"/>
				<keyword text="thyroid"/>
				<keyword text="carcinoma"/>
				<keyword text="tumor"/>
				<keyword text="gland"/>
				<keyword text="endocrine"/>
				<keyword text="medullary"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="Papillary Cancer" id="Papillary Cancer">
				<keyword text="cancer"/>
				<keyword text="thyroid"/>
				<keyword text="carcinoma"/>
				<keyword text="tumor"/>
				<keyword text="gland"/>
				<keyword text="endocrine"/>
				<keyword text="papillary"/>	
				&questionnaire_doc;
				&material_doc;	
			</condition>
			<condition cost="745.00" description="Thyroid Cancer" id="Thyroid Cancer">
				<keyword text="cancer"/>
				<keyword text="thyroid"/>
				<keyword text="carcinoma"/>
				<keyword text="tumor"/>
				<keyword text="gland"/>
				<keyword text="endocrine"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
			<condition cost="745.00" description="FollicularCancer" id="FollicularCancer">
				<keyword text="cancer"/>
				<keyword text="thyroid"/>
				<keyword text="carcinoma"/>
				<keyword text="tumor"/>
				<keyword text="gland"/>
				<keyword text="endocrine"/>
				<keyword text="follicular"/>
				&questionnaire_doc;
				&material_doc;
			</condition>
		</section>
	</department>
</division>
